### ISSUE TITLE
encryption password shown in plaintext

### ISSUE THREAD

**Issue by cptMikky** [xmikos/SnooperStopper#3]
The encryption password, when set, is then immediately shown in a pop-up as plaintext. This is a major security issue and should not be happening, at least not without the user being warned prior showing the password. A security app cannot make any assumptions about users physical environment and must expect all situations to be hostile.

**Comment by xmikos** [comment]
@cptMikky This code is part of Nikolay Elenkov's [Cryptfs Password Manager](https://github.com/nelenkov/cryptfs-password-manager). But you are right, this isn't good assumption. I will change it immediately.

**Comment by cptMikky** [comment]
You just earned a small and insignificant amount of reputation for reacting to security issues fast. Well done ;)

**Comment by xmikos** [comment]
It's fixed, I am now uploading new version to my F-Droid repository. Update in Google Play will take some time.
