### ISSUE TITLE
[feature-request] device wipe after incorrect PIN/password challenge

### ISSUE THREAD

**Issue by revuwa** [xmikos/SnooperStopper#4]
First of all, thanks a lot for your enthusiasm to make and provide this great app!

In business solutions, I've seen a security feature, that your data will be wiped (or simply the encryption key will be deleted), if a wrong PIN or password will be entered 4-times, for example.
I thought, this feature would be perfectly fitting as an optional feature in this awesome app, visually shown like this:
![01_menu](https://cloud.githubusercontent.com/assets/7300276/10103892/cd1968ce-63a6-11e5-9cfc-9e3152a2e6e6.png)

As an suggested user information, there could be a toast message on a failed unlock attempt, like this:
![02_toast_msg](https://cloud.githubusercontent.com/assets/7300276/10103896/d8b6e04e-63a6-11e5-8c7b-227e3d98c145.png)

For me, a feature like this would be the cherry on the cake.

**Comment by xmikos** [comment]
This would be really dangerous option which can lead to unintentional data loss. And if you have strong encryption password, it isn't needed at all. Even NSA with all their resources can't break AES with strong enough key. And quantum computers doesn't affect symmetric ciphers (like AES), only asymmetric public-key algorithms (like RSA).

**Comment by xmikos** [comment]
And I don't think wipe would help you against [rubber-hose cryptoanalysis](https://xkcd.com/538/), it can make things potentially even worse in that case ;-)

**Comment by xmikos** [comment]
But if you really want this option, I am open to pull requests.

**Comment by revuwa** [comment]
Sadly, I'm not a developer and can't provide solid pull requests in this context.
But there exist a FOSS project, which does exactly what I mean: https://github.com/Zyg0te/Locker

It would be great if you would consider to add this project to your credits and use the code from this app to add the feature I've described above.

Thanks in advance for any look into this.
