### ISSUE TITLE
Compatibility with 5.0+ unlock methods

### ISSUE THREAD

**Issue by cptMikky** [xmikos/SnooperStopper#6]
Hi, got a question: is SnooperStopper aware of changes made in 5.0 regarding boot password prompts where a pattern or a numeric PIN can be entered instead of a "password"?

I ask this as I use numeric PIN lock but want to use a stronger password for encryption. However, at boot, I am presented with a PIN pad instaead of keyboard. I tried to change the password in SnooperStopper to a numeric one different from the PIN which works but I am still presented with a numeric keyboard only. I just want to make sure that if I change the password to an actual pass*word*, I'll be presented with full keyboard and be able to enter the password. Using CM12.1 (Android 5.1).

thanks.

**Comment by xmikos** [comment]
Yes, it is compatible with Android 5+, but not compatible with Android 6 yet (but I will add support soon). If you use other chars than digits in your encryption password, you will be presented with full keyboard.

**Comment by utack** [comment]
How is Android 6+ support going?
Currently the app says "Can not get root access" for me

**Comment by utack** [comment]
Found [something on Reddit](https://www.reddit.com/r/cyanogenmod/comments/3znw4c/warning_default_disk_encryption_password_in_cm13/):
`vdc cryptfs changepw password default_password newpwd`
Seems to all you need to do on Cyanogenmod 13 (and also Android 6 it seems)

**Comment by xmikos** [comment]
@utack I didn't have device with Android 6 so far, so I couldn't properly test it. I hope I will find some solution soon, problem seems huge:
[Decryption unsuccessful on N5 running Stock 6.0 with ElementalX 6.03 #14](https://github.com/nelenkov/cryptfs-password-manager/issues/14)

I have looked at `CryptCommandListener.cpp` in AOSP (https://android.googlesource.com/platform/system/vold/) and params are same as in Android 5.x, so this shouldn't affect stock AOSP, only CyanogenMod 13 should be affected.

**Comment by xmikos** [comment]
@utack New version 1.3 supports both stock Android 6 and CyanogenMod 13 (tested on Nexus 5).

**Comment by utack** [comment]
Just tested this on a new CM13 rom, it works perfectly.
Thanks for fixing
