### ISSUE TITLE
Shutdown instead of reboot

### ISSUE THREAD

**Issue by bungabunga** [xmikos/SnooperStopper#7]
Would it be possible to make device shutdown instead of reboot after the wrong pattern/PIN/password attempts?

Why?

I wore my phone in my pocket when working, there was a call but I haven't answered/picked the phone from my pocket. But since I worked fisically and the display remained on for some seconds, the friction in my pocket caused a few wrong PIN "attempts" and my phone got rebooted. But that's not all. The friction caused the boot passphrase to be inserted wrongly a few times and so my phone got factory reset. And when i picked it from my pocket... %#/&$#/  ;) :/

Don't belive it? It happened to me three times.

So I would thank you with all my heart if you could meke (maybe optional) the phone shutdown not reboot after the set number of wrong PIN attempts.

Thanks!

**Comment by xmikos** [comment]
Wow, I didn't think something like that could happend... I hope you didn't lost any important data. I will change it in next version.

**Comment by bungabunga** [comment]
actually i wouldn't belive this story if it didn't happen to me. luckily i had my phone backed up pretty well...

thanks for willingness to solve this issue.

**Comment by xmikos** [comment]
@bungabunga It's done, new version of SnooperStopper is doing shutdown instead of reboot.
